defaults:
  - default.yaml
min_epochs: 1
max_epochs: 2
# prints
profiler: null

# debugs
fast_dev_run: true
overfit_batches: 0
limit_val_batches: 1.0
limit_test_batches: 1.0
detect_anomaly: true
enable_checkpointing: false

callbacks: no_checkpoints.yaml
